"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-25 14:58:40.850000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.Column("stroke", sa.Enum("FR", "BK", "BR", "FL", "IM", name="stroke"), nullable=False),
        sa.Column("course", sa.Enum("SCY", "SCM", "LCM", name="course"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("distance", "stroke", "course", name="uix_event"),
    )
    op.create_table(
        "meets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "swimmers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("birthdate", sa.Date(), nullable=False),
        sa.Column("gender", sa.String(length=10), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meet_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meet_id", sa.Integer(), nullable=False),
        sa.Column("swimmer_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meet_id"],
            ["meets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["swimmer_id"],
            ["swimmers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meet_id", "swimmer_id", "event_id", name="uix_meet_entry"),
    )
    op.create_table(
        "time_standards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("organization", sa.String(length=50), nullable=False),
        sa.Column("age_group", sa.String(length=50), nullable=False),
        sa.Column("gender", sa.String(length=10), nullable=False),
        sa.Column("standard_name", sa.String(length=20), nullable=False),
        sa.Column("standard_rank", sa.Integer(), nullable=False),
        sa.Column("time_seconds", sa.Float(), nullable=False),
        sa.Column("season", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id", "organization", "age_group", "gender", "standard_name", "season", name="uix_time_standard"
        ),
    )
    op.create_table(
        "swim_times",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("meet_entry_id", sa.Integer(), nullable=False),
        sa.Column("time_seconds", sa.Float(), nullable=False),
        sa.Column("notes", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(
            ["meet_entry_id"],
            ["meet_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meet_entry_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("swim_times")
    op.drop_table("time_standards")
    op.drop_table("meet_entries")
    op.drop_table("swimmers")
    op.drop_table("meets")
    op.drop_table("events")
    # ### end Alembic commands ###
